package com.creditsuisse.orderbook.app.repository.domain;

import java.io.Serializable;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entity Class for Order book to save this object in database.
 * 
 * @author Tarun Rohila
 * @since Nov 29, 2018
 */
@Entity
@Table(name = "INSTRUMENT")
@NamedQuery(name = "Instrument.findAll", query = "SELECT o FROM Instrument o")
public class Instrument implements Serializable {
	
	/**
	 * Autogenerated serial number 
	 */
	private static final long serialVersionUID = -1931306263137686364L;

	
	/*
	 * Variable declaration for oid
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long oid;
	
	/*
	 * Variable declaration for name
	 */
	private String name;
	
	@OneToMany(cascade = CascadeType.REMOVE,orphanRemoval = true)
	@JoinColumn(name = "INSTRUMENT_ID", foreignKey = @ForeignKey(name = "none"))
	private Set<OrderBook> orderBook;
	
	/**
	 * Method to get the value of name
	 *
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * Method to set the value for name
	 *
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}


	/**
	 * Method to get the value of oid
	 *
	 * @return the oid
	 */
	public Long getOid() {
		return oid;
	}

	/**
	 * Method to set the value for oid
	 *
	 * @param oid the oid to set
	 */
	public void setOid(Long oid) {
		this.oid = oid;
	}

	/**
	 * Method to get the value of orderBook
	 *
	 * @return the orderBook
	 */
	public Set<OrderBook> getOrderBook() {
		return orderBook;
	}

	/**
	 * Method to set the value for orderBook
	 *
	 * @param orderBook the orderBook to set
	 */
	public void setOrderBook(Set<OrderBook> orderBook) {
		this.orderBook = orderBook;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((oid == null) ? 0 : oid.hashCode());
		result = prime * result + ((orderBook == null) ? 0 : orderBook.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Instrument other = (Instrument) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (oid == null) {
			if (other.oid != null)
				return false;
		} else if (!oid.equals(other.oid))
			return false;
		if (orderBook == null) {
			if (other.orderBook != null)
				return false;
		} else if (!orderBook.equals(other.orderBook))
			return false;
		return true;
	}

	
}
