package com.creditsuisse.orderbook.app.repository.domain;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.creditsuisse.orderbook.app.dto.OrderStatus;

/**
 * Entity Class for Order to save this object in database.
 * 
 * @author Tarun Rohila
 * @since Nov 29, 2018
 */
@Entity
@Table(name = "ORDER_DETAIL")
@NamedQuery(name = "OrderDetail.findAll", query = "SELECT o FROM OrderDetail o")
public class OrderDetail implements Serializable {
	/**
	 * Autogenerated serial number 
	 */
	private static final long serialVersionUID = -1670300190310352579L;
	
	/*
	 * Variable declaration for oid
	 */
	@Id
	@ApiModelProperty(notes = "The database generated ID")
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long oid;
	
	/*
	 * Variable declaration for orderType
	 */
	@ApiModelProperty(notes = "Order type can be limit or market")
	private String orderType;
	
	/*
	 * Variable declaration for status
	 */
	@ApiModelProperty(notes = "Status or order")
	@Enumerated(EnumType.STRING)
	private OrderStatus status;
	
	/*
	 * Variable declaration for quantity
	 */
	@ApiModelProperty(notes = "Quantity of order")
	private int quantity;
	
	/*
	 * Variable declaration for price
	 */
	@ApiModelProperty(notes = "Price limit")
	private Long price;
	
	
	/*
	 * Variable declaration for orderCreationDate
	 */
	@ApiModelProperty(notes = "Event Creation date")
	private String orderCreationDate;
	
	/*
	 * Variable declaration for orderCreationDate
	 */
	@ApiModelProperty(notes = "Order book identifier")
	@Column(name="ORDER_BOOK_ID")
	private Long orderBookId;
	
	@ApiModelProperty(notes = "Instrument identifier")
	@Column(name="INSTRUMENT_ID")
	private Long instrumentId;
	

	/**
	 * Method to get the value of oid
	 *
	 * @return the oid
	 */
	public Long getOid() {
		return oid;
	}

	/**
	 * Method to set the value for oid
	 *
	 * @param oid the oid to set
	 */
	public void setOid(Long oid) {
		this.oid = oid;
	}

	/**
	 * Method to get the value of status
	 *
	 * @return the status
	 */
	public OrderStatus getStatus() {
		return status;
	}

	/**	
	 * Method to set the value for status
	 *
	 * @param status the status to set
	 */
	public void setStatus(OrderStatus status) {
		this.status = status;
	}


	/**
	 * Method to get the value of price
	 *
	 * @return the price
	 */
	public Long getPrice() {
		return price;
	}

	/**
	 * Method to set the value for price
	 *
	 * @param price the price to set
	 */
	public void setPrice(Long price) {
		this.price = price;
	}


	/**
	 * Method to get the value of quantity
	 *
	 * @return the quantity
	 */
	public int getQuantity() {
		return quantity;
	}

	/**
	 * Method to set the value for quantity
	 *
	 * @param quantity the quantity to set
	 */
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	/**
	 * Method to get the value of orderCreationDate
	 *
	 * @return the orderCreationDate
	 */
	public String getOrderCreationDate() {
		return orderCreationDate;
	}

	/**
	 * Method to set the value for orderCreationDate
	 *
	 * @param orderCreationDate the orderCreationDate to set
	 */
	public void setOrderCreationDate(String orderCreationDate) {
		this.orderCreationDate = orderCreationDate;
	}


	/**
	 * Method to get the value of orderType
	 *
	 * @return the orderType
	 */
	public String getOrderType() {
		return orderType;
	}

	/**
	 * Method to set the value for orderType
	 *
	 * @param orderType the orderType to set
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	/**
	 * Method to get the value of orderBookId
	 *
	 * @return the orderBookId
	 */
	public Long getOrderBookId() {
		return orderBookId;
	}

	/**
	 * Method to set the value for orderBookId
	 *
	 * @param orderBookId the orderBookId to set
	 */
	public void setOrderBookId(Long orderBookId) {
		this.orderBookId = orderBookId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((oid == null) ? 0 : oid.hashCode());
		result = prime * result + ((orderCreationDate == null) ? 0 : orderCreationDate.hashCode());
		result = prime * result + ((orderType == null) ? 0 : orderType.hashCode());
		result = prime * result + ((price == null) ? 0 : price.hashCode());
		result = prime * result + quantity;
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetail other = (OrderDetail) obj;
		if (oid == null) {
			if (other.oid != null)
				return false;
		} else if (!oid.equals(other.oid))
			return false;
		if (orderCreationDate == null) {
			if (other.orderCreationDate != null)
				return false;
		} else if (!orderCreationDate.equals(other.orderCreationDate))
			return false;
		if (orderType == null) {
			if (other.orderType != null)
				return false;
		} else if (!orderType.equals(other.orderType))
			return false;
		if (price == null) {
			if (other.price != null)
				return false;
		} else if (!price.equals(other.price))
			return false;
		if (quantity != other.quantity)
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		return true;
	}

	/**
	 * Method to get the value of instrumentId
	 *
	 * @return the instrumentId
	 */
	public Long getInstrumentId() {
		return instrumentId;
	}

	/**
	 * Method to set the value for instrumentId
	 *
	 * @param instrumentId the instrumentId to set
	 */
	public void setInstrumentId(Long instrumentId) {
		this.instrumentId = instrumentId;
	}


}
